apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-express-1
  name: simple-express-1-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/simple-express-1-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-express-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
